# Generated by Django 3.0.6 on 2020-05-07 18:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Other')], default='M', max_length=1)),
                ('nationality', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User_Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('domains', models.CharField(max_length=50)),
                ('work_exp', models.CharField(choices=[('I', 'Intern'), ('S', 'Student'), ('ON', 'Less than 1'), ('TH', 'Less than 3'), ('FI', 'Less than 5')], max_length=2)),
            ],
        ),
    ]
