# Generated by Django 3.0.6 on 2020-05-10 12:14

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_personal',
            name='dob',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_personal',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_professional',
            name='work_exp',
            field=models.CharField(choices=[('F', 'Fresher'), ('S', 'Student'), ('2', '2 yr')], max_length=2),
        ),
    ]
