# Generated by Django 3.0.6 on 2020-05-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_user_personal_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_personal',
            name='pin',
        ),
    ]
