# Generated by Django 3.0.6 on 2020-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_user_personal_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_personal',
            name='dob',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_personal',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
